# Generated by Django 5.2.1 on 2025-05-18 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north', models.FloatField()),
                ('south', models.FloatField()),
                ('east', models.FloatField()),
                ('west', models.FloatField()),
                ('area', models.FloatField(help_text='Area in square kilometers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('road_count', models.IntegerField(default=0)),
                ('congestion', models.IntegerField(default=0, help_text='Congestion score (0-100)')),
                ('ecology', models.IntegerField(default=0, help_text='Ecology score (0-100)')),
                ('pedestrian_friendly', models.IntegerField(default=0, help_text='Pedestrian friendliness score (0-100)')),
                ('public_transport', models.IntegerField(default=0, help_text='Public transport accessibility score (0-100)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analyzed Area',
                'verbose_name_plural': 'Analyzed Areas',
            },
        ),
        migrations.CreateModel(
            name='GreenSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(default='Unnamed green space', max_length=255)),
                ('space_type', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_spaces', to='urban_flow.analyzedarea')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyCongestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('congestion_level', models.IntegerField(help_text='Congestion level (0-100)')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_congestion', to='urban_flow.analyzedarea')),
            ],
            options={
                'ordering': ['hour'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(default='Unnamed road', max_length=255)),
                ('road_type', models.CharField(max_length=50)),
                ('length', models.FloatField(help_text='Length in kilometers')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='urban_flow.analyzedarea')),
            ],
            options={
                'verbose_name': 'Road',
                'verbose_name_plural': 'Roads',
            },
        ),
        migrations.CreateModel(
            name='RoadTypeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_type', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_type_stats', to='urban_flow.analyzedarea')),
            ],
        ),
        migrations.CreateModel(
            name='WaterFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(default='Unnamed water feature', max_length=255)),
                ('feature_type', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_features', to='urban_flow.analyzedarea')),
            ],
        ),
    ]
